train_data_dic_parse = {
    'theia-e3' : ['./dataset/theia-e3/ta1-theia-e3-official-1r.json',
			  './dataset/theia-e3/ta1-theia-e3-official-1r.json.1',
			  './dataset/theia-e3/ta1-theia-e3-official-1r.json.2',
			  './dataset/theia-e3/ta1-theia-e3-official-1r.json.3',
			  './dataset/theia-e3/ta1-theia-e3-official-1r.json.4',
			  './dataset/theia-e3/ta1-theia-e3-official-1r.json.5',
               './dataset/theia-e3/ta1-theia-e3-official-1r.json.6',
                './dataset/theia-e3/ta1-theia-e3-official-1r.json.7',
                 './dataset/theia-e3/ta1-theia-e3-official-1r.json.8',
                  './dataset/theia-e3/ta1-theia-e3-official-1r.json.9',
              ],
    'theia-e5' : [
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.2.json',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.2.json.1',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.3.json',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.3.json.1',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.4.json',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.4.json.1',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.5.json',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.5.json.1',
                   './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.6.json',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.6.json.1',
                   './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.7.json',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.7.json.1',
                   './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.8.json',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.8.json.1',
                   './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.9.json',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.9.json.1',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.10.json',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.10.json.1',
                    './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.11.json',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.11.json.1',

                  ],
    'cadets-e3' :[  './dataset/cadets-e3/ta1-cadets-e3-official.json',
                    './dataset/cadets-e3/ta1-cadets-e3-official.json.1',
                    './dataset/cadets-e3/ta1-cadets-e3-official-1.json',
                    './dataset/cadets-e3/ta1-cadets-e3-official-1.json.1',
                    './dataset/cadets-e3/ta1-cadets-e3-official-1.json.2',
                    './dataset/cadets-e3/ta1-cadets-e3-official-1.json.3',
                    './dataset/cadets-e3/ta1-cadets-e3-official-1.json.4'
                    ],
    'cadets-e5' : [
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.15.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.15.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.16.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.16.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.17.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.17.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.18.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.18.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.19.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.19.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.20.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.20.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.21.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.21.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.22.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.22.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.23.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.23.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.24.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.24.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.25.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.25.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.26.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.26.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.27.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.27.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.28.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.28.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.29.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.29.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.30.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.30.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.31.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.31.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.32.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.32.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.33.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.33.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.34.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.34.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.35.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.35.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.36.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.36.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.37.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.37.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.38.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.38.json.1',
        ],
    'clear-e3' :[
                './dataset/clear-e3/ta1-clearscope-e3-official-2.json.1',
                 './dataset/clear-e3/ta1-clearscope-e3-official-2.json.2',
                 './dataset/clear-e3/ta1-clearscope-e3-official-2.json.3',
                 './dataset/clear-e3/ta1-clearscope-e3-official-2.json.4',
                 './dataset/clear-e3/ta1-clearscope-e3-official-2.json.5',
                 './dataset/clear-e3/ta1-clearscope-e3-official-2.json.6',
                 './dataset/clear-e3/ta1-clearscope-e3-official-2.json.7',
                 './dataset/clear-e3/ta1-clearscope-e3-official-2.json.8',
                 './dataset/clear-e3/ta1-clearscope-e3-official-2.json.9',
                  './dataset/clear-e3/ta1-clearscope-e3-official-2.json.10',
                   './dataset/clear-e3/ta1-clearscope-e3-official-2.json.11',
                 ],
    'clear-e5':[
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.4.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.4.json.1',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.5.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.5.json.1',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.6.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.6.json.1',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.7.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.7.json.1',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.8.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.8.json.1',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.9.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.9.json.1',
    ]
    
}

test_data_dic_parse = {
    'theia-e3' : [
            './dataset/theia-e3/ta1-theia-e3-official-6r.json',
		   './dataset/theia-e3/ta1-theia-e3-official-6r.json.1',
		   './dataset/theia-e3/ta1-theia-e3-official-6r.json.2',
		   './dataset/theia-e3/ta1-theia-e3-official-6r.json.6',
		   './dataset/theia-e3/ta1-theia-e3-official-6r.json.7',
		   './dataset/theia-e3/ta1-theia-e3-official-6r.json.8',
            './dataset/theia-e3/ta1-theia-e3-official-6r.json.9',
            './dataset/theia-e3/ta1-theia-e3-official-6r.json.10',
		   './dataset/theia-e3/ta1-theia-e3-official-6r.json.11',
		   './dataset/theia-e3/ta1-theia-e3-official-6r.json.12'],
    'theia-e5' : [ 
            './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.27.json',
            './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.27.json.1' ,
            './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.28.json',
            './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.28.json.1',
            './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.29.json' ,
            './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.29.json.1',
            './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.30.json',
            ],
    'cadets-e3' : [ 
            './dataset/cadets-e3/ta1-cadets-e3-official.json.2',
            './dataset/cadets-e3/ta1-cadets-e3-official-2.json',
            './dataset/cadets-e3/ta1-cadets-e3-official-2.json.1'],
    'cadets-e5' : [
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.14.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.100.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.100.json.1',
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.108.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.108.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.109.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.109.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.110.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.110.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.116.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.116.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.117.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.117.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.118.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.118.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.119.json',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.119.json.1',
       './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.120.json',

    ],
    'clear-e3' : [
        './dataset/clear-e3/ta1-clearscope-e3-official-2.json.12',
        './dataset/clear-e3/ta1-clearscope-e3-official-2.json.13',
        './dataset/clear-e3/ta1-clearscope-e3-official-2.json.14',
        './dataset/clear-e3/ta1-clearscope-e3-official-2.json.15',
        './dataset/clear-e3/ta1-clearscope-e3-official-2.json.16',
        './dataset/clear-e3/ta1-clearscope-e3-official-2.json.17',
        './dataset/clear-e3/ta1-clearscope-e3-official-2.json.18',
        './dataset/clear-e3/ta1-clearscope-e3-official-2.json.19',
        './dataset/clear-e3/ta1-clearscope-e3-official-2.json.20',
        ],
    'clear-e5':[  
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.19.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.19.json.1',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.20.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.20.json.1',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.21.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.21.json.1',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.22.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.22.json.1',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.23.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.23.json.1',
         './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.28.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.28.json.1',
         './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.29.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.29.json.1',
         './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.30.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.30.json.1',
         './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.31.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.31.json.1'
        
    ]
}

val_data_dic_parse = {
    'theia-e3' : ['./dataset/theia-e3/ta1-theia-e3-official-3.json' , 
                  './dataset/theia-e3/ta1-theia-e3-official-5m.json'],
    'theia-e5' : [ './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.12.json',
                  './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.12.json.1',
                 './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.13.json',
                 './dataset/theia-e5/ta1-theia-1-e5-official-2.bin.13.json.1'],
    'clear-e3':[
                    './dataset/clear-e3/ta1-clearscope-e3-official-2.json.9',
                    './dataset/clear-e3/ta1-clearscope-e3-official-2.json.10',
                   './dataset/clear-e3/ta1-clearscope-e3-official-2.json.11',
                 ],
    'clear-e5':[
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.10.json',
        './dataset/clear-e5/ta1-clearscope-2-e5-official-1.bin.10.json.1'],
    'cadets-e3':[
                    './dataset/cadets-e3/ta1-cadets-e3-official-1.json.4'
                    ],
    'cadets-e5':[
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.53.json',
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.53.json.1',
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.54.json',
         './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.54.json.1',
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.55.json',
         './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.55.json.1',
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.56.json',
         './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.56.json.1',
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.57.json',
         './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.57.json.1',
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.58.json',
         './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.58.json.1',
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.59.json',
         './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.59.json.1',
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.60.json',
         './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.60.json.1',
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.61.json',
         './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.61.json.1',
        './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.62.json',
         './dataset/cadets-e5/ta1-cadets-1-e5-official-2.bin.62.json.1',
    ]
}

def parse_data_list (dataset) :
    train = get_train_dataset(dataset)
    val = get_val_dataset(dataset)
    test = get_test_dataset(dataset)
    return train , val ,  test

def get_train_dataset(dataset) :
    train = train_data_dic_parse[dataset]
    return train

def get_test_dataset(dataset):
    return test_data_dic_parse[dataset]

def get_val_dataset(dataset):
    return val_data_dic_parse[dataset]